services:
  # MySQL Datenbank Service / MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: camunda_mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-camunda}
      MYSQL_USER: ${MYSQL_USER:-camunda}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-camunda}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --transaction-isolation=READ-COMMITTED
      - --innodb-lock-wait-timeout=300
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - camunda_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      start_period: 30s
      interval: 30s

  # Camunda Platform Service
  camunda:
    image: camunda/camunda-bpm-platform:7.23.0
    container_name: camunda_platform
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Datenbankverbindung / Database connection
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-camunda}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      DB_USERNAME: ${MYSQL_USER:-camunda}
      DB_PASSWORD: ${MYSQL_PASSWORD:-camunda}
      # Camunda Admin-Benutzer / Camunda admin user
      CAMUNDA_BPM_ADMIN_USER_ID: admin
      CAMUNDA_BPM_ADMIN_USER_PASSWORD: admin
      CAMUNDA_BPM_ADMIN_USER_FIRST_NAME: Admin
      CAMUNDA_BPM_ADMIN_USER_LAST_NAME: User
      CAMUNDA_BPM_ADMIN_USER_EMAIL: admin@example.com
    ports:
      - "8090:8080"
    networks:
      - camunda_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/camunda/"]
      timeout: 10s
      retries: 10
      start_period: 60s
      interval: 30s


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ie_project_app
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/workspace
    environment:
      # Spring-Profil für Produktion / Spring profile for production
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      # Datenbankverbindung / Database connection
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://mysql:3306/camunda?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-camunda}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-camunda}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:-com.mysql.cj.jdbc.Driver}
      # Camunda-Konfiguration / Camunda configuration
      CAMUNDA_BPM_DATABASE_TYPE: ${CAMUNDA_BPM_DATABASE_TYPE:-mysql}
      CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE: ${CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE:-true}
      # JPA Konfiguration / JPA configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-none}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL:-false}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:-org.hibernate.dialect.MySQL8Dialect}
      # Application Deadline Configuration / Bewerbungsfristen-Konfiguration
      APPLICATION_DEADLINE_WINTER: ${APPLICATION_DEADLINE_WINTER:-2025-08-01}
      APPLICATION_DEADLINE_SUMMER: ${APPLICATION_DEADLINE_SUMMER:-2025-02-01}
      APPLICATION_DEADLINE_MONTHS_BEFORE: ${APPLICATION_DEADLINE_MONTHS_BEFORE:-2}
      JAVA_OPTS: ${JAVA_OPTS:--Xmx512m -Xms256m}
    ports:
      - "8080:8080"
    networks:
      - camunda_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 10
      start_period: 60s
      interval: 30s

    # PHPMyAdmin Service für MySQL / PHPMyAdmin service for MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: camunda_phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "8082:80"
    networks:
      - camunda_network
    restart: unless-stopped

# Docker-Netzwerk für Service-Kommunikation / Docker network for service communication
networks:
  camunda_network:
    driver: bridge

# Persistente Volumes / Persistent volumes
volumes:
  mysql_data:
    driver: local