# Standard-Konfiguration / Default configuration
spring:
  application:
    name: ie-project

  # H2-Datenbank für lokale Entwicklung / H2 database for local development
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  # AJOUT: Configuration des ressources statiques pour éviter les conflits
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
      cache:
        period: 3600

# Camunda-Konfiguration / Camunda configuration
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      first-name: Admin
      last-name: User
      email: admin@example.com
    database:
      schema-update: true
    webapp:
      application-path: /camunda
      # AJOUT: Configuration explicite de l'interface web
      index-redirect-enabled: true
    rest:
      enabled: true
    # AJOUT: Désactiver l'auto-déploiement si problématique
    auto-deployment-enabled: true

# Server-Konfiguration / Server configuration
server:
  port: 8080
  # AJOUT: Configuration des ressources statiques
  error:
    include-stacktrace: on_param
    include-exception: true

# Spring Boot Actuator für health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
  endpoint:
    health:
      show-details: when-authorized

# Logging-Konfiguration / Logging configuration
logging:
  level:
    org.camunda: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.resource: DEBUG
    root: INFO

# Application Deadline Configuration / Bewerbungsfristen-Konfiguration
application:
  deadline:
    # Winter semester deadline (01.08.2025) / Wintersemester-Deadline (01.08.2025)
    winter: "2025-08-01"
    # Summer semester deadline (01.02.2025) / Sommersemester-Deadline (01.02.2025)
    summer: "2025-02-01"
    # Months before deadline for application submission / Monate vor Deadline für Bewerbungseinreichung
    months:
      before: 2

---
# Docker-Profil für Produktionsumgebung / Docker profile for production environment
spring:
  config:
    activate:
      on-profile: docker

  # MySQL-Datenbank für Docker / MySQL database for Docker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/camunda?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:camunda}
    password: ${SPRING_DATASOURCE_PASSWORD:camunda}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

  # JPA-Konfiguration für MySQL / JPA configuration for MySQL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
          format_sql: true
    # AJOUT: Configuration de base de données pour UTF8MB4
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # AJOUT: Configuration des ressources statiques pour Docker
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/
      cache:
        period: 7200

# Camunda-Konfiguration für Docker / Camunda configuration for Docker
camunda:
  bpm:
    database:
      type: ${CAMUNDA_BPM_DATABASE_TYPE:mysql}
      schema-update: ${CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE:true}
    webapp:
      application-path: /camunda
      index-redirect-enabled: true
    # MySQL spezifische Konfiguration / MySQL specific configuration
    generic-properties:
      properties:
        skipIsolationLevelCheck: true
        databaseTablePrefix: ""
        historyTimeToLive: "30"
        jdbcUrl: "jdbc:mysql://mysql:3306/camunda?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"

# Application Deadline Configuration for Docker / Bewerbungsfristen-Konfiguration für Docker
application:
  deadline:
    winter: ${APPLICATION_DEADLINE_WINTER:2025-08-01}
    summer: ${APPLICATION_DEADLINE_SUMMER:2025-02-01}
    months:
      before: ${APPLICATION_DEADLINE_MONTHS_BEFORE:2}

# Actuator endpoints pour Docker
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
  endpoint:
    health:
      show-details: always

# AJOUT: Configuration de logging pour débugger les ressources
logging:
  level:
    org.camunda: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.resource: DEBUG
    root: INFO